### ISSUE TITLE
Archive errors

### ISSUE THREAD

**Issue by ciprianflorescu** [stutrek/Sublime-Text-3-Settings#1]
When I try to unarchive your latest release from this site

https://pypi.python.org/pypi/Pygments

I get errors. Using PeaZip to unarchive on Windows 10.  The error shows up when I try to unarchive the scripts folder.

![capture](https://cloud.githubusercontent.com/assets/11617613/20437793/07552b38-adbe-11e6-80cb-d890e7a3e6d3.PNG)

**Comment by ciprianflorescu** [comment]
It's the find_error.py file which throws this error.

**Comment by stutrek** [comment]
I think you're in the wrong place, this repo is my personal sublime settings.

**Comment by ciprianflorescu** [comment]
Well, I was on this page

https://github.com/stutrek/Sublime-Text-3-Settings/tree/master/Packages/pygments

Which looked like a repo to me and I submitted an issue. There was no way to install pygments from this repo. Sublime just doesn't see it. So I tried the page you listed on that link.

**Comment by ciprianflorescu** [comment]
Searching for the original pygments repo also lists your repo on top.
